## Checker Board Puzzle

How do you cover a checkerboard that has one corner square missing, using L-shaped tiles?

In [28]:
import numpy as np
def generate_problem(n):
    board = [[0]*n for i in range(n)]
    board[n-1][n-1] = -1
    return board
board = generate_problem(8)
print(np.matrix(board))

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1]]


In [29]:
def cover(board, lab=1, top=0, left=0,side=None):
    if not side: side = len(board)
    s = side // 2
    offsets = (0, -1), (side-1, 0)
    for dy_outer, dy_inner in offsets:
        for dx_outer, dx_inner in offsets:
             if not board[top+dy_outer][left+dx_outer]:
                    board[top+s+dy_inner][left+s+dx_inner] = lab
    lab += 1
    if s > 1:
        for dy in [0, s]:
            for dx in [0, s]:
                lab = cover(board, lab, top+dy, left+dx, s)
    return lab 

In [30]:
cover(board)
print(np.matrix(board))

[[ 3  3  4  4  8  8  9  9]
 [ 3  2  2  4  8  7  7  9]
 [ 5  2  6  6 10 10  7 11]
 [ 5  5  6  1  1 10 11 11]
 [13 13 14  1 18 18 19 19]
 [13 12 14 14 18 17 17 19]
 [15 12 12 16 20 17 21 21]
 [15 15 16 16 20 20 21 -1]]


## TopSort in DAGs

In [100]:
def topsort(G):
    visited = [False]*len(G)
    stack =[]

    for i in range(len(G)):
        if visited[i] == False:
                topsort_util(i,visited,stack)
    return stack

def topsort_util(v,visited,stack):
        visited[v] = True
        for idx,i in enumerate(G[v]):
            if i==1:
                if visited[idx] == False:
                    topsort_util(idx,visited,stack)
        stack.insert(0,v)

            

In [60]:
import random
def generate_problem(n):
    return {i:[random.randint(0,1) for _ in range(n)] for i in range(n)}

In [102]:
G = generate_problem(5)
G

{0: [1, 0, 0, 1, 0],
 1: [1, 1, 0, 1, 1],
 2: [1, 1, 0, 1, 0],
 3: [0, 1, 0, 0, 0],
 4: [1, 0, 0, 1, 1]}

In [104]:
topsort(G)

[2, 0, 3, 1, 4]