## Checker Board Puzzle

How do you cover a checkerboard that has one corner square missing, using L-shaped tiles?

In [28]:
import numpy as np
def generate_problem(n):
    board = [[0]*n for i in range(n)]
    board[n-1][n-1] = -1
    return board
board = generate_problem(8)
print(np.matrix(board))

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1]]


In [29]:
def cover(board, lab=1, top=0, left=0,side=None):
    if not side: side = len(board)
    s = side // 2
    offsets = (0, -1), (side-1, 0)
    for dy_outer, dy_inner in offsets:
        for dx_outer, dx_inner in offsets:
             if not board[top+dy_outer][left+dx_outer]:
                    board[top+s+dy_inner][left+s+dx_inner] = lab
    lab += 1
    if s > 1:
        for dy in [0, s]:
            for dx in [0, s]:
                lab = cover(board, lab, top+dy, left+dx, s)
    return lab 

In [30]:
cover(board)
print(np.matrix(board))

[[ 3  3  4  4  8  8  9  9]
 [ 3  2  2  4  8  7  7  9]
 [ 5  2  6  6 10 10  7 11]
 [ 5  5  6  1  1 10 11 11]
 [13 13 14  1 18 18 19 19]
 [13 12 14 14 18 17 17 19]
 [15 12 12 16 20 17 21 21]
 [15 15 16 16 20 20 21 -1]]


## TopSort in DAGs

In [309]:
g = {0: [1, 3, 4], 1: [5], 2: [], 3: [], 4: [], 5: [7], 6: [], 7: []}

In [310]:
visited = [False]*len(g)
stack = []
def topsort(v,visited,stack):
    visited[v] = True
    for i in g[v]:
        if visited[i] == False:
            topsort(i,visited,stack)
    stack.insert(0,v)

for i in range(len(g)):
    if visited[i] == False:
        topsort(i,visited,stack)
stack

[6, 2, 0, 4, 3, 1, 5, 7]

## Subsets of an array

Given an array, print all possible unique subsets

In [264]:
def generate_problem(n):
    return [random.randint(0,100) for _ in range(n)]

In [265]:
x = generate_problem(3)
print(x)
y = generate_problem(10)
y

[54, 49, 2]


[75, 63, 63, 8, 43, 86, 90, 54, 66, 63]

In [290]:
def subset(arr,idx, path):
    res.append(path)
    print(path)
    for i in range(idx, len(arr)):
        if i > idx and arr[i] == arr[i-1]:
            continue
        subset(arr,i+1, path+[arr[i]])

In [291]:
res = []
subset(x,0,[])


print()

res = []
subset(y,0,[])


[]
[54]
[54, 49]
[54, 49, 2]
[54, 2]
[49]
[49, 2]
[2]

[]
[75]
[75, 63]
[75, 63, 63]
[75, 63, 63, 8]
[75, 63, 63, 8, 43]
[75, 63, 63, 8, 43, 86]
[75, 63, 63, 8, 43, 86, 90]
[75, 63, 63, 8, 43, 86, 90, 54]
[75, 63, 63, 8, 43, 86, 90, 54, 66]
[75, 63, 63, 8, 43, 86, 90, 54, 66, 63]
[75, 63, 63, 8, 43, 86, 90, 54, 63]
[75, 63, 63, 8, 43, 86, 90, 66]
[75, 63, 63, 8, 43, 86, 90, 66, 63]
[75, 63, 63, 8, 43, 86, 90, 63]
[75, 63, 63, 8, 43, 86, 54]
[75, 63, 63, 8, 43, 86, 54, 66]
[75, 63, 63, 8, 43, 86, 54, 66, 63]
[75, 63, 63, 8, 43, 86, 54, 63]
[75, 63, 63, 8, 43, 86, 66]
[75, 63, 63, 8, 43, 86, 66, 63]
[75, 63, 63, 8, 43, 86, 63]
[75, 63, 63, 8, 43, 90]
[75, 63, 63, 8, 43, 90, 54]
[75, 63, 63, 8, 43, 90, 54, 66]
[75, 63, 63, 8, 43, 90, 54, 66, 63]
[75, 63, 63, 8, 43, 90, 54, 63]
[75, 63, 63, 8, 43, 90, 66]
[75, 63, 63, 8, 43, 90, 66, 63]
[75, 63, 63, 8, 43, 90, 63]
[75, 63, 63, 8, 43, 54]
[75, 63, 63, 8, 43, 54, 66]
[75, 63, 63, 8, 43, 54, 66, 63]
[75, 63, 63, 8, 43, 54, 63]
[75, 63, 63, 8,

## Combination Sum

Given an array of positive integers arr[] and an integer x, The task is to find all unique combinations in arr[] where the sum is equal to x. 
The same repeated number may be chosen from arr[] an unlimited number of times. Elements in a combination (a1, a2, …, ak) must be printed in non-descending order. (ie, a1 <= a2 <= … <= ak)

In [240]:
def generate_problem(n):
    return [random.randint(0,100) for _ in range(n)],random.randint(0,100)

In [241]:
x = generate_problem(5)
print(x)
y = generate_problem(10)
y

([85, 100, 76, 2, 86], 64)


([8, 34, 26, 19, 62, 81, 49, 87, 70, 91], 90)

In [242]:
def combination_sum(arr, target):
    ans,temp = [],[]
    arr = sorted(list(set(arr)))
    findNumbers(ans, arr, temp, target, 0)
    return ans
 
def findNumbers(ans, arr, temp, target, index):
    if(target == 0):
        ans.append(list(temp))
        return
    for i in range(index, len(arr)):
        if(target - arr[i]) >= 0:
            temp.append(arr[i])
            findNumbers(ans, arr, temp, target-arr[i], i)
            temp.remove(arr[i])

In [243]:
combination_sum(x[0],x[1])

[[2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2,
  2]]

In [244]:
combination_sum(y[0],y[1])

[[8, 8, 8, 8, 8, 8, 8, 8, 26], [8, 8, 8, 8, 8, 8, 8, 34], [19, 19, 26, 26]]

## In order traversal

Given the root of a binary tree, return the inorder traversal of its nodes' values.



In [245]:
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

In [261]:
head = TreeNode(0,left=TreeNode(5,left=TreeNode(3),right=TreeNode(4)),right=TreeNode(15,left=TreeNode(12),right=TreeNode(8)))

In [262]:
result = []
def traversal(root):
    if root == None:
        return

    traversal(root.left)
    result.append(root.val)
    traversal(root.right)
traversal(head)

In [263]:
result

[3, 5, 4, 0, 12, 15, 8]