## Checker Board Puzzle

How do you cover a checkerboard that has one corner square missing, using L-shaped tiles?

In [28]:
import numpy as np
def generate_problem(n):
    board = [[0]*n for i in range(n)]
    board[n-1][n-1] = -1
    return board
board = generate_problem(8)
print(np.matrix(board))

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1]]


In [29]:
def cover(board, lab=1, top=0, left=0,side=None):
    if not side: side = len(board)
    s = side // 2
    offsets = (0, -1), (side-1, 0)
    for dy_outer, dy_inner in offsets:
        for dx_outer, dx_inner in offsets:
             if not board[top+dy_outer][left+dx_outer]:
                    board[top+s+dy_inner][left+s+dx_inner] = lab
    lab += 1
    if s > 1:
        for dy in [0, s]:
            for dx in [0, s]:
                lab = cover(board, lab, top+dy, left+dx, s)
    return lab 

In [30]:
cover(board)
print(np.matrix(board))

[[ 3  3  4  4  8  8  9  9]
 [ 3  2  2  4  8  7  7  9]
 [ 5  2  6  6 10 10  7 11]
 [ 5  5  6  1  1 10 11 11]
 [13 13 14  1 18 18 19 19]
 [13 12 14 14 18 17 17 19]
 [15 12 12 16 20 17 21 21]
 [15 15 16 16 20 20 21 -1]]


## TopSort in DAGs

In [100]:
def topsort(G):
    visited = [False]*len(G)
    stack =[]

    for i in range(len(G)):
        if visited[i] == False:
                topsort_util(i,visited,stack)
    return stack

def topsort_util(v,visited,stack):
        visited[v] = True
        for idx,i in enumerate(G[v]):
            if i==1:
                if visited[idx] == False:
                    topsort_util(idx,visited,stack)
        stack.insert(0,v)

            

In [108]:
g.graph

defaultdict(list, {0: [0], 1: [0, 3], 2: [0, 2, 3], 3: [0, 3], 4: [2, 3]})

In [110]:
def naive_topsort(G, S=None): 

    if S is None: S = set(G) # Default: All nodes
    if len(S) == 1: return list(S) # Base case, single node
    v = S.pop() # Reduction: Remove a node
    seq = naive_topsort(G, S) # Recursion (assumption), n-1
    min_i = 0
    for i, u in enumerate(seq):
        if v in G[u] : min_i = i+1 # After all dependencies
    seq.insert(min_i, v)
    return seq

In [114]:
naive_topsort(g.graph)

[1, 4, 2, 3, 0]

In [113]:
g.topologicalSort()

[4, 2, 1, 3, 0]


In [60]:
import random
def generate_problem(n):
    return {i:[random.randint(0,1) for _ in range(n)] for i in range(n)}

In [102]:
G = generate_problem(5)
G

{0: [1, 0, 0, 1, 0],
 1: [1, 1, 0, 1, 1],
 2: [1, 1, 0, 1, 0],
 3: [0, 1, 0, 0, 0],
 4: [1, 0, 0, 1, 1]}

In [104]:
topsort(G)

[2, 0, 3, 1, 4]

## Subsets of an array

Given an array, print all possible subsets

In [115]:
def generate_problem(n):
    return [random.randint(0,100) for _ in range(n)]

In [195]:
x = generate_problem(3)
print(x)
y = generate_problem(10)
y

[84, 31, 51]


[36, 70, 67, 39, 28, 83, 38, 65, 64, 90]

In [232]:
def subset_generation(arr):
    res = []
    subsets(arr,[],0,res)
    return res
def subsets(arr, subset, index,res):
    res.append(subset)
    for i in range(index, len(arr)):
        subset.append(arr[i])
        subsets(arr, subset, i + 1)
        subset.pop(-1)
    return

prisubset_generation(x,[],0)

print()

subset_generation(x,[],0)


[[], [], [], []]

## Combination Sum

Given an array of positive integers arr[] and an integer x, The task is to find all unique combinations in arr[] where the sum is equal to x. 
The same repeated number may be chosen from arr[] an unlimited number of times. Elements in a combination (a1, a2, …, ak) must be printed in non-descending order. (ie, a1 <= a2 <= … <= ak)

In [202]:
def generate_problem(n):
    return [random.randint(0,100) for _ in range(n)],random.randint(0,100)

In [219]:
x = generate_problem(5)
print(x)
y = generate_problem(10)
y

([52, 24, 53, 51, 32], 30)


([64, 6, 18, 95, 19, 25, 11, 95, 44, 34], 52)

In [220]:
def combination_sum(arr, target):
    ans,temp = [],[]
    arr = sorted(list(set(arr)))
    findNumbers(ans, arr, temp, target, 0)
    return ans
 
def findNumbers(ans, arr, temp, target, index):
    if(target == 0):
        ans.append(list(temp))
        return
    for i in range(index, len(arr)):
 
        if(target - arr[i]) >= 0:
            temp.append(arr[i])
            findNumbers(ans, arr, temp, target-arr[i], i)
            temp.remove(arr[i])

In [229]:
combination_sum(x[0],x[1])

[]

In [228]:
combination_sum(y[0],y[1])

[[6, 6, 6, 6, 6, 11, 11],
 [6, 6, 6, 34],
 [6, 6, 11, 11, 18],
 [11, 11, 11, 19],
 [18, 34]]